package HomeManager.View;

import HomeManager.Controller.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class HomeJFrame extends javax.swing.JFrame implements ActionListener{

  
    
    public HomeJFrame() {
        initComponents();
        
        btnAddCustomer.addActionListener(this);
        btnAddRoom.addActionListener(this);
        btnShowListCustomer.addActionListener(this);
        btnShowListEmptyRoom.addActionListener(this);
        btnShowListRentalRoom.addActionListener(this);
        btnExit.addActionListener(this);
        btnShowStatistics.addActionListener(this);
        btnSort.addActionListener(this);
        
        setLocationRelativeTo(null);
        Util.loadFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddCustomer = new javax.swing.JButton();
        btnAddRoom = new javax.swing.JButton();
        btnShowListCustomer = new javax.swing.JButton();
        btnShowListEmptyRoom = new javax.swing.JButton();
        btnShowStatistics = new javax.swing.JButton();
        btnShowListRentalRoom = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 425));

        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnAddRoom.setText("Add Room");

        btnShowListCustomer.setText("Show List Customer");

        btnShowListEmptyRoom.setText("Show List Room Empty");

        btnShowStatistics.setText("Show Statistics");

        btnShowListRentalRoom.setText("Show List Rental Room");

        btnSort.setText("Sort");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowListCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowListEmptyRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnShowListRentalRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(btnShowStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShowStatistics)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowListRentalRoom)
                        .addGap(18, 18, 18)
                        .addComponent(btnSort)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddRoom)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowListCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowListEmptyRoom)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnShowListCustomer;
    private javax.swing.JButton btnShowListEmptyRoom;
    private javax.swing.JButton btnShowListRentalRoom;
    private javax.swing.JButton btnShowStatistics;
    private javax.swing.JButton btnSort;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btnAddCustomer)) {
            btnAddCustomerClick();
        }
        else if (e.getSource().equals(btnAddRoom)) {
            btnAddRoomClick();
        }
        else if (e.getSource().equals(btnShowListCustomer)) {
            btnShowListCustomerClick();
        }
        else if (e.getSource().equals(btnShowListEmptyRoom)) {
            btnShowListEmptyRoomClick();
        }
        else if (e.getSource().equals(btnShowListRentalRoom)) {
            btnShowListRentalRoomClick();
        }
        else if (e.getSource().equals(btnExit)) {
            btnExitClick();
        }
        else if (e.getSource().equals(btnShowStatistics)) {
            btnShowStatisticsClick();
        }
        else if (e.getSource().equals(btnSort)) {
            btnSortClick();
            
        }
    }

    private void btnAddCustomerClick() {
        new AddCustomerJFrame().setVisible(true);
    }

    private void btnAddRoomClick() {
        new AddRoomJFrame().setVisible(true);
    }

    private void btnShowListCustomerClick() {
        new ShowListCustomerJFrame().setVisible(true);
    }

    private void btnShowListEmptyRoomClick() {
        new ShowListEmptyJFrame().setVisible(true);
    }

    private void btnShowListRentalRoomClick() {
        new ShowListRentalRoomJFrame().setVisible(true);
    }

    private void btnExitClick() {
        Util.writeFile();
        this.dispose();
    }

    private void btnShowStatisticsClick() {
        new ShowStatisticsJFrame().setVisible(true);
    }

    private void btnSortClick() {
        new ShowListRentalRoomSortedJFrame().setVisible(true);
    }
    
    
}
